# Site settings
title: marty learns the codes
email: martymcfly.wa@gmail.com
description: "This is where I leave notes to myself about stuff so I don't forget... about stuff"
baseurl: ""
url: "http://martymcflywa@github.io"
# twitter_username: jekyllrb
github_username:  martymcflywa

# Build settings
markdown: kramdown
permalink: pretty
