# Site settings
title: marty learns the codes
tagline: and other fun bits
description: "This is where I leave notes to myself about stuff so I don't forget... about stuff"
baseurl: ""
url: "http://martymcflywa@github.io"
version: 1.1.1
author: marty
email: martymcfly.wa@gmail.com

# twitter_username: jekyllrb
github_username:  martymcflywa

# Build settings
markdown: rdiscount
permalink: pretty
pygments: true
paginate: 5