# Site settings
title: marty's notebook
tagline: insert note here
description: 
baseurl: /
url: http://martymcflywa.github.io/martymcflywa/
version: 2.1.0
author: marty
email: martymcfly.wa@gmail.com

# twitter_username: jekyllrb
github_username:  martymcflywa
repo: https://github.com/martymcflywa

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty
highlighter: pygments
paginate: 5